### ISSUE TITLE
"pub get" does not work with dart2 from flutter SDK

### ISSUE THREAD

**Issue by xrd** [filiph/edgehead#13]
Running `pub get` with dart2 from flutter sdk does not work for me:

(See this [commit](https://github.com/xrd/edgehead/commit/73ffd37f481865d185e2d623369adac77472aef5))

```
$ pub get
Resolving dependencies... 
Package build_runner has no versions that match >=0.5.0 <0.6.0 derived from:
- edgehead depends on version ^0.5.0
```

Removing `build_runner` from `pubspec.yaml` seems to fix it. After `pub get`, I can run all tests with `pub run test` and the app seems to run fine with `dart bin/play.dart`.

```
$ dart --version
Dart VM version: 2.0.0-dev.28.0.flutter-0b4f01f759 (Tue Feb 20 17:53:06 2018 +0000) on "macos_x64"
$ pub --version
Pub 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
$ which dart
/Users/cdawson/Projects/flutter/bin/cache/dart-sdk/bin/dart
```

**Comment by filiph** [comment]
Hi, thanks for the issue! I'm currently avoiding Dart 2 because it's in flux and because at least one package that I'm using (`code_builder`) requires a major upgrade to run under Dart 2. (This project started ~7 years ago so some of it wasn't coded with Dart 2 in mind.)

Here's my current thinking on upgrading to Dart 2:

---

PROs:

* Gives us `build_runner`
* Unlocks future development (without it, our packages will slowly go out of date, and Flutter will totally elude us)

CONs:

* Too soon and we're dealing with a mess
* Must upgrade `code_builder` (and probably others)

Decision:

* Don't start working on UI before upgrading to Dart 2
* Don't upgrade to Dart 2 until it lands properly

----

Your workaround works, but you're losing source generation. So if you change text files in `/assets/text`, they won't update the code. Similarly for new `Situation`s. That said, you could get pretty far without these.

**Comment by xrd** [comment]
Ok. I'm somewhat new to dart; can you have multiple versions of dart in your path, ie could I run dart 1.x on my machine as well as the dart for flutter? If not, I'll just run inside a docker container to isolate.

Either way, maybe this repository readme should indicate dart 2 isn't supported?

**Comment by filiph** [comment]
Good point.

You can [install Dart](https://www.dartlang.org/install) independently of Flutter (`brew install dart` on macOS). I didn't think Flutter adds Dart to you path automatically. My setup is that I have both Dart and Flutter, and I use the Flutter SDK just for Flutter development, and the standalone Dart for all non-Flutter development (my `which dart` resolves to `/usr/local/bin/dart`).

You could potentially have an alias in your `.bash_profile`, something like `alias dart2='/path/to/flutter/`.

I'll add the notice about Dart 2 to the readme. Thanks for this!

**Comment by filiph** [comment]
I've updated the README with https://github.com/filiph/edgehead/commit/d3f025506bdd07c15da885246b9c4d019fdf86e5. 

I'm closing this one. Dart 2 support is definitely planned but I'll be tracking that work elsewhere.

**Comment by xrd** [comment]
Yes, I added dart to my path on my own, so it would not be a problem for most people. This is great, thanks!
